In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])

In [6]:
arr_1d.ndim

1

In [4]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
arr_2d.ndim

2

In [8]:
arr_2d = np.array([[[1, 2, 3]], [[4, 5, 6]]])

In [9]:
arr_2d.ndim

3

In [10]:
arr_1d.shape

(5,)

In [11]:
arr_float = np.array([1, 2, 3], dtype=np.float64)

In [12]:
arr_float

array([1., 2., 3.])

In [13]:
zeros_arr = np.zeros((3, 4))

In [14]:
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
zeros_arr = np.ones((3, 4))

In [16]:
zeros_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
zeros_arr = np.eye(3)

In [20]:
zeros_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
range_arr = np.arange(0, 10, 2)

In [22]:
range_arr

array([0, 2, 4, 6, 8])

In [25]:
range_arr = np.arange(100, 0, -10)

In [26]:
range_arr

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [27]:
linspace_arr = np.linspace(0, 1, 5) 

In [28]:
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
linspace_arr = np.linspace(0, 10, 500) 

In [30]:
linspace_arr

array([ 0.        ,  0.02004008,  0.04008016,  0.06012024,  0.08016032,
        0.1002004 ,  0.12024048,  0.14028056,  0.16032064,  0.18036072,
        0.2004008 ,  0.22044088,  0.24048096,  0.26052104,  0.28056112,
        0.3006012 ,  0.32064128,  0.34068136,  0.36072144,  0.38076152,
        0.4008016 ,  0.42084168,  0.44088176,  0.46092184,  0.48096192,
        0.501002  ,  0.52104208,  0.54108216,  0.56112224,  0.58116232,
        0.6012024 ,  0.62124248,  0.64128257,  0.66132265,  0.68136273,
        0.70140281,  0.72144289,  0.74148297,  0.76152305,  0.78156313,
        0.80160321,  0.82164329,  0.84168337,  0.86172345,  0.88176353,
        0.90180361,  0.92184369,  0.94188377,  0.96192385,  0.98196393,
        1.00200401,  1.02204409,  1.04208417,  1.06212425,  1.08216433,
        1.10220441,  1.12224449,  1.14228457,  1.16232465,  1.18236473,
        1.20240481,  1.22244489,  1.24248497,  1.26252505,  1.28256513,
        1.30260521,  1.32264529,  1.34268537,  1.36272545,  1.38

In [32]:
np.linspace(1, 9, 9) 

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
random_int = np.random.randint(1, 50, size=(3, 3))

In [40]:
random_int

array([[ 4, 45, 36],
       [38, 20,  7],
       [33, 48, 48]])

In [43]:
random_float = np.random.random((4, 4))

In [44]:
random_float

array([[0.80830638, 0.57991717, 0.04868014, 0.18711235],
       [0.94462675, 0.13913737, 0.27890363, 0.58986507],
       [0.30409758, 0.28392197, 0.7305101 , 0.99509986],
       [0.92758027, 0.89469256, 0.60273264, 0.00110991]])

In [45]:
normal_dist = np.random.normal(0, 1, (3, 3)) 

In [46]:
normal_dist

array([[-0.1000392 , -0.15199065,  0.59774414],
       [-0.20670449, -1.05883005, -0.26840961],
       [-1.77395679,  0.11512082,  0.78484613]])

In [51]:
# Setting seed for reproducibility
np.random.seed(42)
reproducible = np.random.random(5)

In [52]:
reproducible

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [53]:
np.random.seed(25)
reproducible = np.random.random(5)

In [54]:
reproducible

array([0.87012414, 0.58227693, 0.27883894, 0.18591123, 0.41110013])

In [55]:
sample_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [56]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
sample_array.shape

(3, 4)

In [58]:
sample_array.dtype

dtype('int32')

In [59]:
sample_array.ndim

2

In [60]:
sample_array.size

12

In [61]:
sample_array.itemsize

4

In [62]:
arr_1d = np.array([10, 20, 30, 40, 50])

In [63]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [64]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [65]:
data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [66]:
(data > 3) & (data < 8)

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [68]:
np.random.randn(3, 3)

array([[-1.98428727, -1.24691378, -1.69755329],
       [-0.13480646, -0.98481114, -1.16428862],
       [ 0.29431477, -2.03384566,  0.24224829]])

In [69]:
original = np.arange(12) 

In [71]:
original.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
arr_2d.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [74]:
arr_2d.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [76]:
arr_2d.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.array([1, 2, 3, 4, 5],ndmin=8)

array([[[[[[[[1, 2, 3, 4, 5]]]]]]]])

In [78]:
arr_2d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [79]:
arr_2d.mean()

5.0

In [80]:
arr_2d.max()

9

In [82]:
sample_array[2]

array([ 9, 10, 11, 12])

In [83]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
sample_array[:,2]

array([ 3,  7, 11])

In [86]:
sample_array[:2,:1]

array([[1],
       [5]])

In [87]:
sample_array.mean()

6.5

In [88]:
sample_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [89]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
sample_array.mean(axis=0)

array([5., 6., 7., 8.])

In [91]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [92]:
a

array([1, 2, 3, 4])

In [93]:
a*2

array([2, 4, 6, 8])

In [94]:
a+b

array([ 6,  8, 10, 12])

In [95]:
a*b

array([ 5, 12, 21, 32])

In [96]:
b/a

array([5.        , 3.        , 2.33333333, 2.        ])

In [97]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [98]:
b-a

array([4, 4, 4, 4])

In [99]:
a.dot(b)

70