In [6]:
import numpy as np

In [7]:
angles = np.array([0, np.pi/4, np.pi/2, np.pi])

In [9]:
angles

array([0.        , 0.78539816, 1.57079633, 3.14159265])

In [10]:
np.sin(angles)

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 1.22464680e-16])

In [11]:
np.cos(angles)

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -1.00000000e+00])

In [12]:
np.tan(angles[:3])

array([0.00000000e+00, 1.00000000e+00, 1.63312394e+16])

In [13]:
values = np.array([1, 2, 3, 4])

In [14]:
np.exp(values)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [15]:
np.log(values)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [16]:
np.log10(values)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [17]:
np.sqrt(values)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [18]:
decimals = np.array([1.234, 2.567, 3.891])

In [22]:
np.round(decimals, 2)

array([1.23, 2.57, 3.89])

In [23]:
np.ceil(decimals)

array([2., 3., 4.])

In [24]:
np.floor(decimals)

array([1., 2., 3.])

In [25]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

In [26]:
v_stack = np.vstack((arr1, arr2))

In [27]:
v_stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
h_stack = np.hstack((arr1, arr2))

In [29]:
h_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [30]:
concat_axis0 = np.concatenate((arr1, arr2), axis=0)

In [31]:
concat_axis0

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
large_array = np.arange(20).reshape(4, 5)

In [33]:
large_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
split_result = np.split(large_array, 2, axis=0) 

In [35]:
split_result

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [41]:
split_result = np.split(large_array, 2.5, axis=1) 

In [42]:
split_result

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19]])]

In [43]:
data_with_missing = np.array([1.0, 2.0, np.nan, 4.0, 5.0, np.inf])

In [44]:
data_with_missing

array([ 1.,  2., nan,  4.,  5., inf])

In [45]:
masked_data = np.ma.masked_invalid(data_with_missing)

In [46]:
masked_data

masked_array(data=[1.0, 2.0, --, 4.0, 5.0, --],
             mask=[False, False,  True, False, False,  True],
       fill_value=1e+20)